apiVersion: batch/v1
kind: Job
metadata:
  generateName: blender-render-
spec:
  template:
    spec:
      containers:
      - name: blender
        image: quay.io/openshiftdemos/blender-remote:latest
        env:
          - name: BLEND_LOCATION
            valueFrom:
              configMapKeyRef:
                name: render-details
                key: blend_location
          - name: RENDER_TYPE
            valueFrom:
              configMapKeyRef:
                name: render-details
                key: render_type
          - name: S3_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: render-details
                key: s3_endpoint
          - name: S3_KEY
            valueFrom:
              configMapKeyRef:
                name: render-details
                key: s3_key
          - name: S3_SECRET
            valueFrom:
              configMapKeyRef:
                name: render-details
                key: s3_secret
      restartPolicy: Never
  backoffLimit: 1
